site_name: "NetBox HealthCheck Plugin"
site_description: "NetBox plugin for HealthCheck."
repo_url: https://github.com/netbox-community/netbox-healthcheck-plugin
repo_name: "netbox-community/netbox-healthcheck-plugin"
site_url: https://netbox-community.github.io/netbox-healthcheck-plugin
strict: true

theme:
  name: material
  features:
    - content.code.copy
    - navigation.top
    - navigation.tracking
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.emoji
  - pymdownx.snippets:
      base_path: ['.']
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Configuration: configuration.md
  - Releases: releases.md
  - Development:
      - Contributing: development/contributing.md
      - Releasing: development/releasing.md
