# See PEP 518 for the spec of this file
# https://www.python.org/dev/peps/pep-0518/

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name =  "netbox-healthcheck-plugin"
version = "0.3.0"
authors = [
    { name = "NetBox Labs", email = "support@netboxlabs.com" }
]
maintainers = [
    { name = "NetBox Labs", email = "support@netboxlabs.com" }
]
description = "NetBox plugin for HealthCheck."
readme = "README.md"

classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Natural Language :: English',
    "Programming Language :: Python :: 3 :: Only",
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
]

requires-python = ">=3.12.0"

dependencies = [
    'django-health-check>=4.2.2,<5',
    'redis>=4.0',
]

[project.optional-dependencies]
test = [
    "ruff>=0.15.0",
    "check-manifest>=0.49",
    "pre-commit>=3.9.0",
    "pytest>=8.3.0",
    "pytest-django>=4.9.0",
]
docs = [
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.0",
]

[project.urls]
Documentation = "https://github.com/netbox-community/netbox-healthcheck-plugin/blob/main/README.md"
Source = "https://github.com/netbox-community/netbox-healthcheck-plugin"
Tracker = "https://github.com/netbox-community/netbox-healthcheck-plugin/issues"

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["F", "E", "W", "I", "UP", "C4", "B", "SIM", "TCH"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["netbox_healthcheck_plugin"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "netbox_healthcheck_plugin.tests.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
pythonpath = ["."]
testpaths = ["netbox_healthcheck_plugin/tests"]

[tool.setuptools]
packages = ["netbox_healthcheck_plugin", "netbox_healthcheck_plugin.backends", "netbox_healthcheck_plugin.tests"]

[tool.setuptools.package-data]
netbox_healthcheck_plugin = ["templates/**"]
